imports:
  - { resource: ./controllers/application.yaml }
  - { resource: ./shared/application.yaml }
  - { resource: ./users/application.yaml }
  - { resource: ./categories/application.yaml }
  - { resource: ./products/application.yaml }
  - { resource: ./stores/application.yaml }
