services:
  Categories.domain.CategoryRepository:
    class: ../../../../modules/categories/infrastructure/persistence/typeOrmCategoryRepository
    arguments: ['@Shared.ConnectionManager']

  Categories.application.CategoryCreator:
    class: ../../../../modules/categories/application/categoryCreator
    arguments: ['@Categories.domain.CategoryRepository']

  Categories.application.CategoryFinder:
    class: ../../../../modules/categories/application/categoryFinder
    arguments: ['@Categories.domain.CategoryRepository']

  Categories.application.CategoryAllFinder:
    class: ../../../../modules/categories/application/categoryAllFinder
    arguments: ['@Categories.domain.CategoryRepository']

  Categories.application.CategoryUpdater:
    class: ../../../../modules/categories/application/categoryUpdater
    arguments: ['@Categories.domain.CategoryRepository']

  Categories.application.CategoryDeleter:
    class: ../../../../modules/categories/application/categoryDeleter
    arguments: ['@Categories.domain.CategoryRepository']
