services:

  Controllers.status.StatusGetController:
    class: ../../../status/statusGetController
    arguments: []

  Controllers.users.UserPutController:
    class: ../../../users/userPutController
    arguments: ['@Users.application.UserRegistrar']

  Controllers.users.UserGetController:
    class: ../../../users/userGetController
    arguments: ['@Users.application.UserFinder']

  Controllers.users.UserPostAuthController:
    class: ../../../users/userPostAuthController
    arguments: ['@Users.application.UserAuthenticator', '@Users.domain.UserTokenSigner']

  Controllers.categories.CategoryPutController:
    class: ../../../categories/categoryPutController
    arguments: ['@Categories.application.CategoryCreator', '@Categories.application.CategoryUpdater', '@Categories.application.CategoryFinder']

  Controllers.categories.CategoryGetController:
    class: ../../../categories/categoryGetController
    arguments: ['@Categories.application.CategoryFinder']

  Controllers.categories.CategoryGetAllController:
    class: ../../../categories/categoryGetAllController
    arguments: ['@Categories.application.CategoryAllFinder']

  Controllers.categories.CategoryDeleteController:
    class: ../../../categories/categoryDeleteController
    arguments: ['@Categories.application.CategoryDeleter']
